### ISSUE TITLE
Add single and multiple page run bot buttons on main page of https://iabot.toolforge.org/

### ISSUE THREAD

**Issue by jorlowitz** [internetarchive/internetarchivebot#17] opened 2021-03-31 18:42 UTC
Improve UX by putting the main bot use triggers front and center, with a short description of which one to use when.

**Comment by decodedfile** [comment] 2021-04-03 06:40
Duplicate of #

**Comment by Nintendofan885** [comment] 2021-04-09 09:49
@jorlowitz  Hi, issues should be posted on Phabricator instead. I've moved this to https://phabricator.wikimedia.org/T279766

**Closed** 2021-04-21 20:24 UTC
